apiVersion: v1
kind: Namespace
metadata:
  name: opsradar

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: opsradar
data:
  FRONTEND_URL: "http://opsradar-frontend:3000"
  BASE_API_PATH: "/api"
  POSTGRE_DB_URL: "opsradar-postgre-svc:5432"
  DB_USER: "postgres"
  DB_NAME: "opsradar"

---
apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: opsradar
type: generic
stringData:
  DB_PASSWORD: "admin123"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: opsradar-backend
  namespace: opsradar
  labels:
    app: opsradar
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: opsradar
      tier: backend
  template:
    metadata:
      labels:
        app: opsradar
        tier: backend
    spec:
      imagePullSecrets:
        - name: ecr-registry-helper
      containers:
        - name: opsradar-backend
          image: 691456441865.dkr.ecr.us-east-2.amazonaws.com/opsradar-python
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          envFrom:
            - configMapRef:
                name: backend-config
            - secretRef:
                name: backend-secret

---
apiVersion: v1
kind: Service
metadata:
  name: "opsradar-backend"
  namespace: "opsradar"
spec:
  selector:
    app: opsradar
    tier: backend
  type: ClusterIP
  ports:
    - port: 5000
      targetPort: 5000
