apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: opsradar
  name: opsradar-db
  labels:
    app: opsradar
    tier: db
spec:
  selector:
    matchLabels:
      app: opsradar
      tier: db
  serviceName: opsradar-postgre-svc
  replicas: 1
  minReadySeconds: 10
  template:
    metadata:
      labels:
        app: opsradar
        tier: db
    spec:
      imagePullSecrets:
        - name: ecr-registry-helper
      terminationGracePeriodSeconds: 10
      containers:
        - name: opsradar-db
          image: 691456441865.dkr.ecr.us-east-2.amazonaws.com/opsradar-postgre
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: DB_PASSWORD
                  name: backend-secret
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  key: DB_NAME
                  name: backend-config
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  key: DB_USER
                  name: backend-config
          volumeMounts:
            - name: opsradar-pvc
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: opsradar-pvc
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: standard
        resources:
          requests:
            storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  namespace: opsradar
  name: opsradar-postgre-svc
  labels:
    app: opsradar
    tier: db
spec:
  clusterIP: None
  selector:
    app: opsradar
    tier: db
  ports:
    - port: 5432
      targetPort: 5432
